### ISSUE TITLE
慢查询sql现在不能按照时间排序，不能看最新的慢sql~

### ISSUE THREAD

**Issue by lizuo123** [housepower/ckman#101]
![image](https://user-images.githubusercontent.com/24853659/122704155-aecbb080-d285-11eb-979d-332559131d31.png)

**Comment by yuzhichang** [comment]
好建议。后续将增加如下组件：时间范围选择、Limit设置。

**Comment by YenchangChan** [comment]
we implement it on #114 
we can sort lists by query start time and also assgin limit and time range
<img width="1454" alt="图片" src="https://user-images.githubusercontent.com/43897067/124547824-57216d80-de5f-11eb-9d0a-01a3ecd31e86.png">
