### ISSUE TITLE
集群创建对hosts文件的修改和格式问题

### ISSUE THREAD

**Issue by darkfwin** [housepower/ckman#108]
1. 为了管理集群机器方便，ck-001节点上hosts配置所有机器（ck-001至ck-011））的映射，在001至008节点创建replica集群时，hosts文件失去了009至011机器的映射关系，需要重新添加这三台机器的域名映射，hosts体现为覆盖
2. 在009至011机器上覆盖安装集群时，hosts体现是追加，但格式有错误，如下图
<img width="289" alt="WechatIMG228" src="https://user-images.githubusercontent.com/53214880/123200451-542f9000-d4e3-11eb-987a-dc292b9b2735.png">

建议：无论是全新部署集群还是覆盖安装，完善对hosts文件的修改逻辑，有相关映射更新相关映射，没有则追加。

**Comment by YenchangChan** [comment]
this is a bug caused by use goroutine to ensure hosts.

**Comment by YenchangChan** [comment]
fixed on #113
