### ISSUE TITLE
通过域名访问管理界面，经常报Ip不匹配

### ISSUE THREAD

**Issue by guoxiaolongzte** [housepower/ckman#175]
后台看日志，报错信息如下：
2021-11-24T10:09:29.315+0800    ERROR   model/response.go:24    GET /api/v1/ck/cluster return 5023, <nil>
github.com/housepower/ckman/model.WrapMsg
        /root/go/src/github.com/housepower/ckman/model/response.go:24

**Comment by YenchangChan** [comment]
Related to the logic of obtaining token, and obtaining token depends on client ip， so...just not support.

**Comment by YenchangChan** [comment]
cannot be reproduced
