### ISSUE TITLE
创建集群失败

### ISSUE THREAD

**Issue by w3z4y4** [housepower/ckman#179]
4台服务器，逐台创建是成功的
选择多副本，一次性部署4台服务器失败。
开了debug日志，只能看到如下报错
![IMG_20211212_114749.jpg](https://user-images.githubusercontent.com/18455415/145699536-298d3986-1a30-404e-9c94-bbdf13d7ad43.jpg)

**Comment by yuzhichang** [comment]
ckman在部署后5秒检查clickhouse-server是否可达。可能是5s超时不够长，或者clickhouse-server由于某个原因启动失败。

**Comment by w3z4y4** [comment]
> ckman在部署后5秒检查clickhouse-server是否可达。可能是5s超时不够长，或者clickhouse-server由于某个原因启动失败。

您好，我刚刚测试了下用ckman部署。
虽然还是部署失败了，但是我检查了下日志，说配置文件已经分发到各个服务器上。
有的服务器配置文件有缺失，缺少macros.xml metrika.xml,没台情况都不一样
请问下这种情况应该如何继续分析

**Comment by yuzhichang** [comment]
@w3z4y4 用的ckman版本？如果不是最新的，换最新的试试。理论上ckman日志说配置文件已经分发到各个服务器上，就不会有缺少macros.xml之类的事情。

**Comment by w3z4y4** [comment]
> @w3z4y4 用的ckman版本？如果不是最新的，换最新的试试。理论上ckman日志说配置文件已经分发到各个服务器上，就不会有缺少macros.xml之类的事情。

@yuzhichang 我们用的最新的2.2.2版本，clickhouse用的21.8.9.13 lts
![IMG_20211213_104704.jpg](https://user-images.githubusercontent.com/18455415/145744759-752f5c7b-e3d7-4d52-9282-81b72ef934b3.jpg)
日志中有这些信息，但是没有macros关键字
![IMG_20211213_105024.jpg](https://user-images.githubusercontent.com/18455415/145745443-9f648d26-a764-4bef-b9cf-30b6d8c790a3.jpg)
我把配置文件目录清空重新安装后，配置文件只有以下内容![IMG_20211213_105908.jpg](https://user-images.githubusercontent.com/18455415/145745563-764c5165-f202-456a-a79b-fba24edbff07.jpg)

**Comment by YenchangChan** [comment]
这个问题在这个commit已经修复： https://github.com/housepower/ckman/commit/fbae0dea1ab64166b56ed2788bbc1f72809b50b7
workaround方案：创建集群时不要指定逻辑集群，或者自己最新main分支下载代码编译打包。
预计本周会发布修复版本。

**Comment by yuzhichang** [comment]
@w3z4y4 v2.2.3发布
