### ISSUE TITLE
添加ClickHouse集群节点失败

### ISSUE THREAD

**Issue by chinayangze** [housepower/ckman#180]
添加ClickHouse集群节点失败: Incorrect ATTACH TABLE query for Atomic database engine. Use one of the following queries instead: 1. ATTACH TABLE COLUMNS; 2. CREATE TABLE COLUMNS <table definition>; 3. ATTACH TABLE COLUMNS FROM '/path/to/data/' <table definition>; 4. ATTACH TABLE COLUMNS UUID '<uuid>' <table definition>;

**Comment by YenchangChan** [comment]
请提供如下信息：
1. clickhouse使用版本
2. 原始节点是否有比较特殊的表
3. ckman的报错日志

**Comment by chinayangze** [comment]
> 请提供如下信息：
> 
> 1. clickhouse使用版本
> 2. 原始节点是否有比较特殊的表
> 3. ckman的报错日志

ClickHouse版本: 21.11.4.14，ckman管理平台 v2.2.3

原始节点是否没有比较特殊的表，新建集群 一次性添加6个节点没有问题， 但是先添加4个节点，再加2个节点就会报错， 但是新加的节点clickhouse-server服务是正常的， 只是添加不进ckman

[root@cdh85-86 ~]# clickhouse status
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 69739.
The process with pid = 69739 is running.

ckman的报错日志：

[root@cdh85-86 ~]# cat /var/log/clickhouse-server/clickhouse-server.err.log
2021.12.15 13:36:58.755283 [ 69739 ] {} <Warning> Application: Calculated checksum of the binary: 7EA717A3C1A90B36D60B3CBB669F1A73. There is no information about the reference checksum.
2021.12.15 13:36:58.770582 [ 69739 ] {} <Warning> Access(local directory): File /ckdata/clickhouse/access/users.list doesn't exist
2021.12.15 13:36:58.770595 [ 69739 ] {} <Warning> Access(local directory): Recovering lists in directory /ckdata/clickhouse/access/
2021.12.15 13:37:17.387439 [ 69793 ] {ff361e8d-1b00-4756-8f80-00896b78a7ee} <Warning> InterpreterCreateQuery: ATTACH TABLE query with full table definition is not recommended: use either ATTACH TABLE COLUMNS; to attach existing table or CREATE TABLE COLUMNS <table definition>; to create new table or ATTACH TABLE COLUMNS FROM '/path/to/data/' <table definition>; to create new table and attach data.
2021.12.15 13:37:17.389071 [ 69793 ] {ff361e8d-1b00-4756-8f80-00896b78a7ee} <Error> executeQuery: Code: 80. DB::Exception: Incorrect ATTACH TABLE query for Atomic database engine. Use one of the following queries instead:
1. ATTACH TABLE COLUMNS;
2. CREATE TABLE COLUMNS <table definition>;
3. ATTACH TABLE COLUMNS FROM '/path/to/data/' <table definition>;
4. ATTACH TABLE COLUMNS UUID '<uuid>' <table definition>;. (INCORRECT_QUERY) (version 21.12.1.9017 (official build)) (from [::ffff:172.20.85.111]:16439) (in query: ATTACH VIEW COLUMNS (`table_catalog` String, `table_schema` String, `table_name` String, `column_name` String, `ordinal_position` UInt64, `column_default` String, `is_nullable` UInt8, `data_type` String, `character_maximum_length` Nullable(UInt64), `character_octet_length` Nullable(UInt64), `numeric_precision` Nullable(UInt64), `numeric_precision_radix` Nullable(UInt64), `numeric_scale` Nullable(UInt64), `datetime_precision` Nullable(UInt64), `character_set_catalog` Nullable(String), `character_set_schema` Nullable(String), `character_set_name` Nullable(String), `collation_catalog` Nullable(String), `collation_schema` Nullable(String), `collation_name` Nullable(String), `domain_catalog` Nullable(String), `domain_schema` Nullable(String), `domain_name` Nullable(String), `column_comment` String, `column_type` String, `TABLE_CATALOG` String ALIAS table_catalog, `TABLE_SCHEMA` String ALIAS table_schema, `TABLE_NAME` String ALIAS table_name, `COLUMN_NAME` String ALIAS column_name, `ORDINAL_POSITION` UInt64 ALIAS ordinal_position, `COLUMN_DEFAULT` String ALIAS column_default, `IS_NULLABLE` UInt8 ALIAS is_nullable, `DATA_TYPE` String ALIAS data_type, `CHARACTER_MAXIMUM_LENGTH` Nullable(UInt64) ALIAS character_maximum_length, `CHARACTER_OCTET_LENGTH` Nullable(UInt64) ALIAS character_octet_length, `NUMERIC_PRECISION` Nullable(UInt64) ALIAS numeric_precision, `NUMERIC_PRECISION_RADIX` Nullable(UInt64) ALIAS numeric_precision_radix, `NUMERIC_SCALE` Nullable(UInt64) ALIAS numeric_scale, `DATETIME_PRECISION` Nullable(UInt64) ALIAS datetime_precision, `CHARACTER_SET_CATALOG` Nullable(String) ALIAS character_set_catalog, `CHARACTER_SET_SCHEMA` Nullable(String) ALIAS character_set_schema, `CHARACTER_SET_NAME` Nullable(String) ALIAS character_set_name, `COLLATION_CATALOG` Nullable(String) ALIAS collation_catalog, `COLLATION_SCHEMA` Nullable(String) ALIAS collation_schema, `COLLATION_NAME` Nullable(String) ALIAS collation_name, `DOMAIN_CATALOG` Nullable(String) ALIAS domain_catalog, `DOMAIN_SCHEMA` Nullable(String) ALIAS domain_schema, `DOMAIN_NAME` Nullable(String) ALIAS domain_name, `COLUMN_COMMENT` String ALIAS column_comment, `COLUMN_TYPE` String ALIAS column_type) AS SELECT database AS table_catalog, database AS table_schema, table AS table_name, name AS column_name, position AS ordinal_position, default_expression AS column_default, type LIKE 'Nullable(%)' AS is_nullable, type AS data_type, character_octet_length AS character_maximum_length, character_octet_length, numeric_precision, numeric_precision_radix, numeric_scale, datetime_precision, NULL AS character_set_catalog, NULL AS character_set_schema, NULL AS character_set_name, NULL AS collation_catalog, NULL AS collation_schema, NULL AS collation_name, NULL AS domain_catalog, NULL AS domain_schema, NULL AS domain_name, comment AS column_comment, type AS column_type FROM system.columns), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa20c85a in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&) @ 0x13180c54 in /usr/bin/clickhouse
2. DB::InterpreterCreateQuery::assertOrSetUUID(DB::ASTCreateQuery&, std::__1::shared_ptr<DB::IDatabase> const&) const @ 0x13180a64 in /usr/bin/clickhouse
3. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x131867df in /usr/bin/clickhouse
4. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x131824b8 in /usr/bin/clickhouse
5. DB::InterpreterCreateQuery::execute() @ 0x13189ecb in /usr/bin/clickhouse
6. ? @ 0x134cfa90 in /usr/bin/clickhouse
7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x134cd875 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0x13f7d5d1 in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0x13f90e59 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x16ee1b6f in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x16ee3fc1 in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x16ff2d49 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x16ff0440 in /usr/bin/clickhouse
14. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
15. __clone @ 0xfe02d in /usr/lib64/libc-2.17.so

2021.12.15 13:37:17.389185 [ 69793 ] {ff361e8d-1b00-4756-8f80-00896b78a7ee} <Error> TCPHandler: Code: 80. DB::Exception: Incorrect ATTACH TABLE query for Atomic database engine. Use one of the following queries instead:
1. ATTACH TABLE COLUMNS;
2. CREATE TABLE COLUMNS <table definition>;
3. ATTACH TABLE COLUMNS FROM '/path/to/data/' <table definition>;
4. ATTACH TABLE COLUMNS UUID '<uuid>' <table definition>;. (INCORRECT_QUERY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa20c85a in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&, char const*&, std::__1::shared_ptr<DB::IAST>&) @ 0x13180c54 in /usr/bin/clickhouse
2. DB::InterpreterCreateQuery::assertOrSetUUID(DB::ASTCreateQuery&, std::__1::shared_ptr<DB::IDatabase> const&) const @ 0x13180a64 in /usr/bin/clickhouse
3. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x131867df in /usr/bin/clickhouse
4. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x131824b8 in /usr/bin/clickhouse
5. DB::InterpreterCreateQuery::execute() @ 0x13189ecb in /usr/bin/clickhouse
6. ? @ 0x134cfa90 in /usr/bin/clickhouse
7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x134cd875 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0x13f7d5d1 in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0x13f90e59 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x16ee1b6f in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x16ee3fc1 in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x16ff2d49 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x16ff0440 in /usr/bin/clickhouse
14. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
15. __clone @ 0xfe02d in /usr/lib64/libc-2.17.so

**Comment by aipan** [comment]
我也遇到了相同的问题。
ClickHouse版本: 21.12.2.17，ckman管理平台 v2.2.3
日志
2021-12-18T14:28:40.079+0800    ERROR   runner/runner.go:58     clickhouse.addnode failed:code: 80, message: Incorrect ATTACH TABLE query for Atomic database engine. Use one of the following queries instead:
1. ATTACH TABLE COLUMNS;
2. CREATE TABLE COLUMNS <table definition>;
3. ATTACH TABLE COLUMNS FROM '/path/to/data/' <table definition>;
4. ATTACH TABLE COLUMNS UUID '<uuid>' <table definition>;
github.com/housepower/ckman/service/runner.(*RunnerService).CheckTaskEvent.func1
        /root/go/src/github.com/housepower/ckman/service/runner/runner.go:58
github.com/housepower/ckman/common.runFunc
        /root/go/src/github.com/housepower/ckman/common/workerpool.go:80
github.com/housepower/ckman/common.(*WorkerPool).wokerFunc
        /root/go/src/github.com/housepower/ckman/common/workerpool.go:57

**Comment by YenchangChan** [comment]
目前看来是新版clickhouse的兼容问题，ckman 需要做新版本的兼容。

**Comment by YenchangChan** [comment]
#212 fixed it
