### ISSUE TITLE
运行sql报错

### ISSUE THREAD

**Issue by xsaffable** [housepower/ckman#191]
<p>
问题: 我在运行一个带注释的 sql 的时候，出现了报错，但是在 client 执行并不会报错，sql 如下: <br>

select
	1 as id, -- id
	'张三' as name, -- 用户名
	22 as age

报错如下:

> query ClickHouse failed: Syntax error: failed at position 75 ('10000') (line 2, col 8): 10000. Expected one of: UNION, LIMIT, WHERE, WINDOW, DoubleColon, LIKE, GLOBAL NOT IN, end of query, HAVING, AS, DIV, IS, UUID, GROUP BY, INTO OUTFILE, EXCEPT, OR, identifier, QuestionMark, BETWEEN, OFFSET, NOT LIKE, MOD, PREWHERE, AND, Comma, alias, ORDER BY, SETTINGS, IN, ILIKE, INTERSECT, FROM, FORMAT, Dot, NOT ILIKE, WITH, NOT, Arrow, token, NOT IN, GLOBAL IN

</p>

<p>
我想提交一个 pr 来修复这个问题，修改计划如下: <br>
1. 不再替换换行符<br>
2. 最后拼接 limit，先换行再拼接 limit，防止被最后注释失效
</p>

**Comment by YenchangChan** [comment]
#192 fixed
