### ISSUE TITLE
可以增加额外的配置设置能力和配置模板保存能力

### ISSUE THREAD

**Issue by lingo-xp** [housepower/ckman#194]
1.在实际使用中经常会需要用到额外的config.xml中配置，比如zookeeper多集群<auxiliary_zookeepers> 之类，如果可以在ckman中添加额外系统配置选项把配置生成在custom.xml中，或者提供用户自定义的xml文件上传到config.d中也是非常好的
2.对于很多配置比如像磁盘策略之类能提供模板保存的能力会更便捷

**Comment by YenchangChan** [comment]
后续会提供专家模式定义或修改配置，用户可在界面自定义ck的一些高级选项，具体实现细节还没想好，反正已经有规划去做了。

**Comment by yuzhichang** [comment]
v2.2.4添加了对自定义设置的支持。
