### ISSUE TITLE
docker安装的zookeeper和ckman

### ISSUE THREAD

**Issue by shouziws** [housepower/ckman#205]
docker安装的zookeeper和ckman 如何来部署clickhouse，会出现无法部署的原因

**Comment by YenchangChan** [comment]
建议把zk的配置以及部署时具体报错信息贴一下。已尝试：docker安装的zookeeper是可以部署的

**Comment by shouziws** [comment]
https://github.com/housepower/ckman/issues/205#issuecomment-1098829233

> 建议把zk的配置以及部署时具体报错信息贴一下。已尝试：docker安装的zookeeper是可以部署的

**Comment by shouziws** [comment]
![image](https://user-images.githubusercontent.com/33045888/163391236-51d76ee7-360f-4829-b1c3-2c51bcb97b9a.png)
![image](https://user-images.githubusercontent.com/33045888/163391260-150c870d-8242-4c97-9fea-e3b4269b1818.png)
这是我部署zookeeper的方式

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
