### ISSUE TITLE
Table Metrics 显示问题

### ISSUE THREAD

**Issue by chenxiaoliang0901** [housepower/ckman#22]
Table Metrics 好像只显示default下的表，其它库的表如何显示出来呢

**Comment by yuzhichang** [comment]
Confirmed as a bug.

**Comment by yuzhichang** [comment]
https://github.com/housepower/ckman/pull/21 fixed this.

**Comment by yuzhichang** [comment]
Fix has been released in https://github.com/housepower/ckman/releases/tag/v1.2.9.
