### ISSUE TITLE
如何永久关闭表监控自动刷新

### ISSUE THREAD

**Issue by zy857189690** [housepower/ckman#221]
怎么通过配置的方式关闭实时刷新，发现对部署ckman的机器，同时这个台机器后clickhouse 造成cpu90%+ 
![image](https://user-images.githubusercontent.com/42372535/169790680-a5a5eb76-1e9b-4b1e-ae00-f42bdce3bb3a.png)

**Comment by YenchangChan** [comment]
直接关闭实时就行了啊
![image](https://user-images.githubusercontent.com/43897067/169856132-edbc9d53-a80c-44dc-9a4c-d7721c679c82.png)

**Comment by zy857189690** [comment]
重新登录以后或者整个网页刷新又还是默认恢复5秒了

**Comment by yuzhichang** [comment]
@zy857189690 后续将优化前端，使得各帐号、各页面的刷新频度持久化到浏览器localStorage。

**Comment by YenchangChan** [comment]
https://github.com/housepower/ckman-fe/pull/49 fixed.
