### ISSUE TITLE
导入集群时候，提示权限问题

### ISSUE THREAD

**Issue by ChaoHsupin** [housepower/ckman#237]
ckman版本：2.2.5
使用默认用户名密码登录：
![截屏2022-06-25 下午4 08 21](https://user-images.githubusercontent.com/34222824/175764628-685a3f66-2dd9-4fc2-93d1-03acbd13008c.png)
![截屏2022-06-25 下午4 10 39](https://user-images.githubusercontent.com/34222824/175764699-0a22ddf5-d9e5-4b96-930e-055b7eab4830.png)
重新登录后问题还在。

**Comment by yuzhichang** [comment]
ckman之前有nginx/haproxy?

**Comment by ChaoHsupin** [comment]
是的，用ip直接访问可以的。
