### ISSUE TITLE
上传较大安装包时，卡住错误问题

### ISSUE THREAD

**Issue by zolawuzhigang** [housepower/ckman#245]
上传较大安装包时，存在进度条卡在48%，47%的情况，有时会提示网络错误，刷新页面后安装包有上传记录，已上传去pakcage目录下面对比安装包大小时，发现上传的安装包相比原来小了很多M，换了其他服务器部署，还是存在这种情况
![image](https://user-images.githubusercontent.com/104047841/177917651-67f550a9-6759-4354-9b0a-2cef55da5d80.png)

![image](https://user-images.githubusercontent.com/104047841/177917727-24934b88-9bd8-4d30-8dbd-148be40b21f9.png)

**Comment by zolawuzhigang** [comment]
![image](https://user-images.githubusercontent.com/104047841/177917877-9f9131fe-e221-4c4f-a40d-ac8cee3ffa36.png)
![image](https://user-images.githubusercontent.com/104047841/177923230-3e53d269-9fb3-4574-aba4-c30eda0cfe92.png)
过了一个小时还是不动

**Comment by YenchangChan** [comment]
安装包不要上传那么多，dbg包不要传，只需要client，server，common三个包就行了。

**Comment by YenchangChan** [comment]
dbg是调试版本，安装包非常大，我们实际也不会安装。

**Comment by zolawuzhigang** [comment]
嗯呢，非常感谢，问题已解决，关闭issue
