### ISSUE TITLE
接口说明存在无法访问问题

### ISSUE THREAD

**Issue by zolawuzhigang** [housepower/ckman#246]
![image](https://user-images.githubusercontent.com/104047841/177918369-eff12bec-bd33-4f99-a093-550f9a2e412c.png)
![image](https://user-images.githubusercontent.com/104047841/177918390-beb20e54-6fac-4598-b5e4-7a8cceeba86b.png)

**Comment by YenchangChan** [comment]
需要在ckman.yaml中添加 `swagger_enable: true` 选项，详见文档说明。
