### ISSUE TITLE
一个ckman的bug

### ISSUE THREAD

**Issue by shouziws** [housepower/ckman#253]
通过ckman创建了集群，然后在面板上把集群销毁了，在用相同的集群名字去创建会出现 create task failed, cluster %s has another task already running

**Comment by YenchangChan** [comment]
什么版本？看看消息中心有什么显示？

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
