### ISSUE TITLE
ckman创建clickhouse集群报错，版本是v2.1.3

### ISSUE THREAD

**Issue by lijingzhuang** [housepower/ckman#259]
目录：/etc/clickhouse-server/config.d中的custom.xml文件，集群安装的时候下面的参数始终是冒号
<listen_host>::</listen_host> 
这样导致启动失败，需要每台机器手动启动然后导入集群，想咨询下如何修改

**Comment by yuzhichang** [comment]
已解决问题。升级到最新版试试。

**Comment by lijingzhuang** [comment]
您好，请问有ckman技术交流群吗？想跟大佬学习技术



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhichang ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 上午10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [housepower/ckman] ckman创建clickhouse集群报错，版本是v2.1.3 (Issue #259)





 
已解决问题。升级到最新版试试。

**Comment by yuzhichang** [comment]
https://github.com/housepower/ckman#about-us
