### ISSUE TITLE
ssh：握手失败：ssh：无法验证，尝试的方法[无公钥]，没有支持的方法

### ISSUE THREAD

**Issue by rwrepoadmin** [housepower/ckman#264]
大家好
我正在嘗試使用 ssh 密鑰設置 clickhouse 集群。我可以通過命令行從主機 ssh 到集群機器。
我還復制了 ckman 工作目錄中的密鑰和授權密鑰。

創建集群時出現錯誤

無效參數：主機 93.184.216.34 獲取平台失敗：主機：93.184.216.34，cmd：uname -m：：ssh：握手失敗：ssh：無法驗證，嘗試的方法 [none publickey]，沒有支持的方法

**Comment by YenchangChan** [comment]
请提供更多的日志，以及创建集群时的配置参数

**Comment by xiaosmile3628** [comment]
您好，请问这个有解决吗？我现在在生产环境部署遇到同样的问题

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
