### ISSUE TITLE
错误提示： 获取复制表状态失败: zk: node does not exist

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#27]
tables复制表监控出现错误信息
![image](https://user-images.githubusercontent.com/50901800/115495863-1f148080-a29b-11eb-8964-3f46778ac674.png)

layer初始化的时候可以优化到配置文件吗
<macros>
		<layer>01</layer>
		<shard>03</shard>
		<replica>vm185</replica>
	</macros>

**Comment by zhbdesign** [comment]
<macros>
		<layer>01</layer>
		<shard>03</shard>
		<replica>srt185</replica>
	</macros>

**Comment by zhbdesign** [comment]
> <macros>
		<layer>01</layer>
		<shard>03</shard>
		<replica>srt185</replica>
	</macros>

**Comment by zhbdesign** [comment]
> 
<macros>
		<layer>01</layer>
		<shard>03</shard>
		<replica>srt185</replica>
	</macros>

**Comment by zhbdesign** [comment]
`<macros>
		<layer>01</layer>
		<shard>03</shard>
		<replica>srt185</replica>
	</macros>`

**Comment by YenchangChan** [comment]
你的表创建时指定的`zookeeper`路径是什么？ `replicated_table metric`监控的是`/clickhouse/tables/{cluster}/{shard}/{database}` 这个节点，如果不在这个路径下，就会报znode节点不存在。
建议使用ckman自带的api创建表，这样就能正常展示了。

**Comment by zhbdesign** [comment]
> 你的表创建时指定的`zookeeper`路径是什么？ `replicated_table metric`监控的是`/clickhouse/tables/{cluster}/{shard}/{database}` 这个节点，如果不在这个路径下，就会报znode节点不存在。
> 建议使用ckman自带的api创建表，这样就能正常展示了。

在初始化数据库以后，就显示这个错误，应该是获取指标的逻辑没考虑这个情况，另外，有交流群吗？

**Comment by YenchangChan** [comment]
有交流群，请加我微信： yudinghou，我拉你进群。

**Comment by YenchangChan** [comment]
we  will fetch zookeeper path from ck in future.
