### ISSUE TITLE
ckman修改replica相关参数失败，疑似bug

### ISSUE THREAD

**Issue by HwiLu** [housepower/ckman#270]
原先ck集群副本和分片为以下方案
![3b829028f770e285faaed1fea20246d](https://user-images.githubusercontent.com/25824870/217154916-539eb950-f0c5-4e4f-b689-b5afc137eac1.png)

我希望修改为三个副本一个分片，在ckman前台增加以下自定义参数，并勾选强制覆盖，后保存重启
![12abe88a518e47889b5f707bde84343](https://user-images.githubusercontent.com/25824870/217155049-43a85da3-2799-46be-b0b8-137b4e30d07e.png)

查看ck后台配置文件，发现有点段配置无法被覆盖掉

![de9e6bb7012f21550620e6fb5c2b211](https://user-images.githubusercontent.com/25824870/217155238-a35a7a18-1cf6-4fa5-beeb-c11519ac23f0.png)

查询分片信息发现配置新增成功，但是不符合要求

![e5cf00dd6356416c0289c127f5162df](https://user-images.githubusercontent.com/25824870/217155316-6468c1d8-2773-4f7d-a61f-99ca4e7a2520.png)

ckman前台显示也未发生变化，如下所示
![3b829028f770e285faaed1fea20246d](https://user-images.githubusercontent.com/25824870/217155344-10f39bff-385d-4eb0-b98f-9e73572ce8a3.png)

**Comment by HwiLu** [comment]
还是说我xpath写的不对 ，ckman 版本是2.3.5

**Comment by yuzhichang** [comment]
应当点击“增加节点” 来为特定shard增加一个副本

**Comment by yuzhichang** [comment]
ckman v2.3.5支持缩减shard数目。

**Comment by HwiLu** [comment]
我想请问，问题还没有解决，issue就关闭了这正常吗

**Comment by HwiLu** [comment]
我们只有三个节点，默认是2个分片，但是最后一个分片只有一个副本，我希望修改为总共一个分片，三个副本。这个ck集群已经上线了，请问使用ckman应该如何修改？不能直接删节点再添加节点的吧。
