### ISSUE TITLE
api如何访问

### ISSUE THREAD

**Issue by HwiLu** [housepower/ckman#271]
[get]   http://ip:8808/api/v1/ck/config
使用浏览器打开上述api地址什么也没有返回

**Comment by YenchangChan** [comment]
你的需求是什么？ckman没有提供这个api

**Comment by HwiLu** [comment]
记错了。
这个[GET]/api/v1/config
我想测试api是否可以正常使用，哪这个api做个例子

**Comment by YenchangChan** [comment]
ckman访问需要token鉴权的，可以登录ckman获取到token后，使用postman或者curl之类的工具，在header里填上token即可访问，如果是想通过代码集成ckman的接口调用，可参考：  https://segmentfault.com/a/1190000040413551

**Comment by HwiLu** [comment]
收到 谢谢
