### ISSUE TITLE
[均衡集群]操作页面一直显示加载中

### ISSUE THREAD

**Issue by xiaosmile3628** [housepower/ckman#272]
【ckman版本】
2.2.11 
【操作系统架构】
arm架构
【clickhouse版本】
21.9.5.16（自行编译适应arm架构）
【问题描述】
1. 在2分片2副本的clickhouse集群基础上增加第三分片,操作成功后，点击管理集群的均衡集群操作，页面一直提示加载中。
2. 集群中有4张表，数据量总共4000万左右
3. 查看日志，没有ERROR，最后一行INFO日志内容：business/ck_rebalance.go:113 host:x.x.x.x, command: ssh -o StrictHostKeyChecking=false x.x.x.x ls /data/server/clickhouse-21.9.5.16/data//clickhouse/data/ckpadmi002db 
4. 手动在命令行执行上述操作正常显示数据库中的4张表

**Comment by YenchangChan** [comment]
猜测可能集群各节点之间没有配置互信导致

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
