### ISSUE TITLE
rpm安装后按文档修改密码。报找不到ckmanpassword的错误。

### ISSUE THREAD

**Issue by AlabLan** [housepower/ckman#278]
1.安装的是2.3.6的RPM包，安装完成后 /etc/ckman/conf 目录下并无ckmanpassword 可执行文件，直接执行ckmanpassword报找不到命令的错误。
[https://img1.imgtp.com/2023/07/03/GvzHl5TJ.png](https://img1.imgtp.com/2023/07/03/GvzHl5TJ.png) 
2.如要修改密码，按文档描述是执行ckmanpassword后会直接生成password文件，那如何控制新密码的生成，ckmanpasswoord可以添加啥指定新密码的参数吗？否则假设生成了新的password文件，但文件内容是加密后的密码，如何知道新密码明文。

**Comment by YenchangChan** [comment]
ckmanpasswd是一个二进制文件，rpm方式安装的话在/usr/local/bin下，该命令会在/etc/ckman/conf下生成一个password的密文，登录时会根据该密文校验密码。没有提供根据密文查询明文的手段。

**Comment by AlabLan** [comment]
那请问如果运行完后生成了password密文，此时web端登录时并不知道生成的password密文对应的明文密码啊，要怎么登录？

**Comment by YenchangChan** [comment]
密码不是你自己改的吗？你肯定知道呀

**Comment by AlabLan** [comment]
okok,感谢，我一直以为是ckmanpasswd 后面传一个参数当作密文，但又害怕猜错结果还生成了密文覆盖了默认密码，所以一直不敢运行，一运行才发现里面写的很清晰，感谢。
