### ISSUE TITLE
docker启动创建集群，ClickHouse Version下拉框是空

### ISSUE THREAD

**Issue by hanwei1970** [housepower/ckman#28]
![image](https://user-images.githubusercontent.com/76390748/115520893-31071b00-a2bd-11eb-864c-61388aea7da2.png)
ClickHouse Version

**Comment by zhbdesign** [comment]
> ![image](https://user-images.githubusercontent.com/76390748/115520893-31071b00-a2bd-11eb-864c-61388aea7da2.png)
> ClickHouse Version

你upload安装包了吗，上传后就会出现版本了

**Comment by YenchangChan** [comment]
@zhbdesign 说的是正确的，需要先上传安装包，因为部署集群是要根据你上传的安装包去各个节点部署的。
