### ISSUE TITLE
创建的集群利用ckman修改了default用户的默认密码后，采用明文保存密码

### ISSUE THREAD

**Issue by AlabLan** [housepower/ckman#280]
可否后续将default的密码采用<password_sha256_hex>模式保存？如果我将配置文件手动改成<password_sha256_hex>xyxyxyxyx</password_sha256_hex> 的形式，ckman会受影响吗？

**Comment by YenchangChan** [comment]
不太好做，因为ckman的原则是保持原始配置文件不变，所有新增的配置都放在config.d和users.d下面，因为默认的users.xml里已经指定了default用户的密码使用明文方式了，如果要改成加密存储，就得修改掉默认的users.xml
