### ISSUE TITLE
bin/start 启动失败

### ISSUE THREAD

**Issue by melin** [housepower/ckman#29]
![image](https://user-images.githubusercontent.com/1145830/115577981-70eaf400-a2f7-11eb-8e4d-0b8fc931c4fc.png)

**Comment by YenchangChan** [comment]
是否没有配置nacos？把配置文件里nacos的enable改为false再试试。

**Comment by zhbdesign** [comment]
可以看下日志，确定是否启动成功，是否有错误

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
