### ISSUE TITLE
session接口有数据，前端没显示

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#32]
![image](https://user-images.githubusercontent.com/50901800/115660576-cb736700-a36e-11eb-977f-4c6a45839988.png)

**Comment by YenchangChan** [comment]
open sessions：展示的是 当前正在 运行的查询语句；
slow sessions：展示的是7天内查询最耗时的SQL语句；
你看到的api返回的信息并不在这里 展示。
具体请看文档的解释。

**Comment by YenchangChan** [comment]
Fix has been released in https://github.com/housepower/ckman/releases/tag/v1.3.1
