### ISSUE TITLE
简单查询页面可以做一下分页处理

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#35]
![image](https://user-images.githubusercontent.com/50901800/115673281-0a111d80-a37f-11eb-8bce-b8dcfe3cd5ab.png)

**Comment by YenchangChan** [comment]
https://github.com/housepower/ckman-fe/commit/68a2acfbebff49c84ab8f6b6fe21906a6d7a193a

**Comment by YenchangChan** [comment]
v1.3.4 release
