### ISSUE TITLE
集群导入之后无法显示node信息

### ISSUE THREAD

**Issue by tcjin** [housepower/ckman#37]
集群导入之后前端界面显示导入成功，集群列表有一条记录，但是记录中没有node信息，查看后台日志也无报错，cluster.json中hosts为空

**Comment by tcjin** [comment]
![image](https://user-images.githubusercontent.com/83052513/115822958-042b4300-a438-11eb-859c-b1d21bff2c3b.png)
![image](https://user-images.githubusercontent.com/83052513/115822965-08576080-a438-11eb-9dce-891d0860fcea.png)
![image](https://user-images.githubusercontent.com/83052513/115822979-0db4ab00-a438-11eb-8ba7-96455e886232.png)

**Comment by YenchangChan** [comment]
请确保集群导入时，ck集群健康可用，且zookeeper及ck的节点填写正确。参考文档说明：
> Cluster Name: 节点名称，该名称必须是确实存在的集群名，且不能与ckman中已有的集群名字重复。
ClickHouse Node IP: clickhouse节点ip列表，以逗号分隔
ClickHouse TCP Port: ck节点TCP端口，默认为9000
Zookeeper Node List: zk节点列表
ZooKeeper Port: zk端口，默认为2181
ZK Status Port: zookeeper指标监控的端口，默认8080
Cluster Username: ck的用户名
Cluster Password: ck的密码

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
