### ISSUE TITLE
ck集群导入之后节点无法展示，但是普罗米修斯监控的指标却可以展示

### ISSUE THREAD

**Issue by tcjin** [housepower/ckman#40]
ck集群导入之后节点无法展示，但是普罗米修斯监控的指标却可以展示
![image](https://user-images.githubusercontent.com/83052513/115837798-8e30d700-a44b-11eb-8a5a-3c83cac6480d.png)
![image](https://user-images.githubusercontent.com/83052513/115837827-9721a880-a44b-11eb-9b48-216eff7b9d9e.png)

**Comment by YenchangChan** [comment]
the same as #37

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
