### ISSUE TITLE
bug: 新建一个复制表再删除。 刷新`Tables`页面出现500

### ISSUE THREAD

**Issue by FishermanZzhang** [housepower/ckman#42]
如果在zk 中也删除这个复制表信息， 则正常显示

**Comment by YenchangChan** [comment]
后面 会增加 zk的清理机制

**Comment by YenchangChan** [comment]
fixed on #44

**Comment by zhbdesign** [comment]
> fixed on #44

![image](https://user-images.githubusercontent.com/50901800/116353079-c14ae000-a828-11eb-97e0-0b3dce9a8dc3.png)
