### ISSUE TITLE
schemer工具执行查询建库建表语句认证失败

### ISSUE THREAD

**Issue by FoolishWall** [housepower/ckman#47]
原因：使用remote时没有带上ck用户与密码

报错日志如下：FATAL   schemer/schemer.go:148  got error code: 516, message: default: Authentication failed: password is incorrect or there is no user with such name

相关代码（需要作如下调整）
```
// getCreateReplicaObjects returns a list of objects that needs to be created on a host in a cluster
func getCreateReplicaObjects(db *sql.DB) (names, statements []string, err error) {
	system_tables := fmt.Sprintf("remote('%s', system, tables, '%s', '%s')", cmdOps.SrcHost, cmdOps.ChUser, cmdOps.ChPassword)
        ...
}
```

**Comment by yuzhichang** [comment]
ClickHouse官方文档建议default用户仅用于集群结点之间，且不设置密码。

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
