### ISSUE TITLE
集群元数据管理

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#53]
维护各个Clickhosue集群的元数据信息，包含表的元数据信息及Clickhouse服务状态信息，给用户更直观的元数据管理体验，主要有如下功能：

1.查询指定集群和库表信息，同时展示该表的状态：只读 or 读写。

2.查看表的元数据信息 行数、磁盘占用、原始大小、更新时间、分区信息等。

3.设定数据生命周期，基于分区数对数据进行清理操作。

**Comment by yuzhichang** [comment]
1. 该表的只读状态  -- 这个在哪里查询？
2. 行数、磁盘占用、原始大小 已展示。更新时间  在哪里查询？分区信息 可以有
3. ckman 有API将指定时间范围的数据archive到指定的HDFS。有API删除时间范围的数据。

**Comment by zhbdesign** [comment]
> 1. 该表的只读状态  -- 这个在哪里查询？
> 2. 行数、磁盘占用、原始大小 已展示。更新时间  在哪里查询？分区信息 可以有
> 3. ckman 有API将指定时间范围的数据archive到指定的HDFS。有API删除时间范围的数据。

![image](https://user-images.githubusercontent.com/50901800/116492717-8ea7f280-a8cf-11eb-8936-4307d2cd202a.png)

**Comment by zhbdesign** [comment]
system.parts中的max_date和max_time是否代表了更新时间

**Comment by yuzhichang** [comment]
system.parts中的max_date和max_time 代表的是数据中的ORDER BY的那个时间列的最大值。不是更新时间。

**Comment by FishermanZzhang** [comment]
datadog参考资料：
1. 监控页面：https://www.datadoghq.com/blog/monitor-clickhouse/
2. 监控数据：https://docs.datadoghq.com/integrations/clickhouse/?tab=host
3. 实现： https://github.com/DataDog/integrations-core/blob/master/clickhouse/datadog_checks/clickhouse/queries.py

**Comment by zhbdesign** [comment]
> datadog参考资料：
> 
> 1. 监控页面：https://www.datadoghq.com/blog/monitor-clickhouse/
> 2. 监控数据：https://docs.datadoghq.com/integrations/clickhouse/?tab=host
> 3. 实现： https://github.com/DataDog/integrations-core/blob/master/clickhouse/datadog_checks/clickhouse/queries.py

https://iteblog.blog.csdn.net/article/details/111351075，也可以参考此博客里的内容，包括配置文件编排，前端功能等

**Comment by YenchangChan** [comment]
https://github.com/housepower/ckman/issues/99#issuecomment-874479449
