### ISSUE TITLE
用户管理

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#54]
通过web平台展示users.xml中对应权限的profiles 和 quotas，运维人员只需根据用户属性选择对应的配置填写对应的用户名及自动生成的密文密码即可，不会影响已配置好的权限及资源，同时每次xml操作都会提前备份文件，在xml修改异常时可随时回滚

**Comment by zhbdesign** [comment]
字节云服务的用户权限可以参考[https://docs.bytehouse.cn/zh-cn/docs/%E7%94%A8%E6%88%B7%E6%9D%83%E9%99%90%E7%AE%A1%E7%90%86](url)

**Comment by YenchangChan** [comment]
implement by #223
