### ISSUE TITLE
添加ck集群配置文件修改功能

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#56]
由于ck集群的特殊性，每个实例的配置文件都是不同的，实例较多的情况下，手动修改配置文件非常容易发生错误，从而导致不可逆的结果，包括修改config.xml以及user.xml

**Comment by yuzhichang** [comment]
高级 - xml编辑器展示模板 - 应用配置变更        可以考虑这样

**Comment by zhbdesign** [comment]
> 高级 - xml编辑器展示模板 - 应用配置变更 可以考虑这样

可以参考腾讯的ck配置修改功能
![image](https://user-images.githubusercontent.com/50901800/118930424-4c2a8080-b978-11eb-8a1e-2d4cac4fadd7.png)

**Comment by zhbdesign** [comment]
> 腾讯云仓库ClickHouse操作指南 https://cloud.tencent.com/document/product/1299/49826

官方的配置说明集中在两个地方，config.xml：https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/，
user.xml：https://clickhouse.tech/docs/en/operations/settings/settings/，
 
但是还是有配置没有出现在官网，我提了issue在ck，希望能做一个维护的配置清单https://github.com/ClickHouse/ClickHouse/issues/24322

**Comment by yuzhichang** [comment]
https://github.com/housepower/ckman/pull/139 实现了集群配置管理
