### ISSUE TITLE
We're sorry but ckman doesn't work properly without JavaScript enabled. Please enable it to continue.

### ISSUE THREAD

**Issue by taiyang-li** [housepower/ckman#57]
Where can it enable it ?

**Comment by yuzhichang** [comment]
参考https://stackoverflow.com/questions/55459339/how-to-solve-noscript-doesnt-work-properly-without-javascript-enabled-when-se。
你是如何启动ckman的？这类问题一般是前端开发人员用命令行运行nodejs调试前端代码遇到的。

**Comment by taiyang-li** [comment]
按照官方文档启动的，编译打包后运行`cd ckman && sudo ./bin/start`

**Comment by YenchangChan** [comment]
不知道你编译的是什么版本？1.3.1版本简化了编译步骤，前端已经打包好了，无需编译，应该不会出现这种提示，如果还存在问题，建议直接下载发行版本运行：https://github.com/housepower/ckman/releases/tag/v1.3.1
