### ISSUE TITLE
无法添加节点

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#59]
添加ClickHouse集群节点失败: URL "192.168.31.38:9000" is not allowed in config.xml

**Comment by zhbdesign** [comment]
添加节点时metrika.xml已经更新，新节点也已经成功安装和启动，ckman出现了问题

**Comment by zhbdesign** [comment]
添加节点时metrika.xml已经更新，新节点也已经成功安装和启动，ckman出现了问题

**Comment by zhbdesign** [comment]
![image](https://user-images.githubusercontent.com/50901800/118581196-cb2a8800-b7c3-11eb-8953-220fd6a8e25a.png)

**Comment by YenchangChan** [comment]
the same  as #78
