### ISSUE TITLE
zk znode无法获取到

### ISSUE THREAD

**Issue by IVitamin-C** [housepower/ckman#64]
zk 版本 3.5.8 
通过ckman创建的集群无法正常获取znode。
![image](https://user-images.githubusercontent.com/35019926/117523314-c78c4980-afea-11eb-9ba9-781b344be0f8.png)

**Comment by YenchangChan** [comment]
ckman是什么版本？1.3.1版本修复了非标准路径下  zk node 不存在的问题，如果集群是导入的还需要注意是否有除了{cluster}和{shard}以外的macros，目前ckman只支持解析这两个宏。

第二个报错是取zk的版本号逻辑 有点问题，将在下个版本修复。

**Comment by IVitamin-C** [comment]
1.3.0版本 集群是由ckman创建的

**Comment by YenchangChan** [comment]
This issue has not been active for 1 month, so we decided to close it. If you have any questions, please reopen a new issue.
