### ISSUE TITLE
ckman在创建集群时的ssh操作无法过滤服务器登陆时可能产生的无效信息

### ISSUE THREAD

**Issue by huzhichengdd** [housepower/ckman#66]
问题描述，在安装好ckman进行create cluster操作时，系统会抛出如下错误:
![image](https://user-images.githubusercontent.com/83016994/117528837-d254d780-b006-11eb-8e96-41ddc720a382.png)
图片文字描述：“初始化组件失败: strconv.Atoi: parsing "id: cannot find name for group ID 10000\n65726092": invalid syntax”

其中，在通过用户名密码手动ssh服务器的时候，系统会给我抛一个/usr/bin/id: cannot find name for group ID 10000；。
通过cat /proc/meminfo | grep MemTotal | awk '{print $2}'可在服务器上得到65726092这串数字，这是取机器的物理内存地址。

问题应该明确了，在通过用户名密码手动ssh服务器的时候，系统会给我抛一个/usr/bin/id: cannot find name for group ID 10000，但是不影响服务器登陆。而通过ckman导入集群进行ssh操作的话，他会处理服务器的一个返回字符串，正常情况下应该只返回那一串内存地址，即65726092，但是服务器可能会抛出一些登陆信息，如抛出的/usr/bin/id: cannot find name for group ID 10000也会夹带进去，导致无法进行内存解析，造成此错误。

解决方案，在ssh服务器时过滤掉服务器登陆时返回的无效信息。

**Comment by YenchangChan** [comment]
we will filter stderr from result when ssh run shell script (#115 )
