### ISSUE TITLE
ck21.4版本需要添加remote_url_allow_hosts的ip或者把remote_url_allow_hosts删除

### ISSUE THREAD

**Issue by zhbdesign** [housepower/ckman#78]
![image](https://user-images.githubusercontent.com/50901800/118608955-dba32880-b7ec-11eb-8343-cef6d8ee1bf0.png)

**Comment by zhbdesign** [comment]
ClickHouse release v20.1.2.4, 2020-01-22
ClickHouse release 21.4.1 2021-04-12，应该是这个版本间隔，v20.1.2.4开始的这个属性，21.4.1改变的

**Comment by yuzhichang** [comment]
fixed by #79
