### ISSUE TITLE
已有集群可以通过修改clusters.json的方式来实现集群管理吗？

### ISSUE THREAD

**Issue by KelovpString** [housepower/ckman#83]
如题，导入已有集群只能是import模式，无法进行分区平衡、升级等功能，那可以修改clusters.json，使得其配置和导入模式一致，是否可以正常使用对应功能？

**Comment by YenchangChan** [comment]
理论上是可以的，但不排除存在其他风险，请谨慎操作。

**Comment by KelovpString** [comment]
> 理论上是可以的，但不排除存在其他风险，请谨慎操作。

ok 感谢
