### ISSUE TITLE
query_log ttl

### ISSUE THREAD

**Issue by yuzhichang** [housepower/ckman#84]
https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/

```
<query_log>
    <database>system</database>
    <table>query_log</table>
    <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
    <flush_interval_milliseconds>7500</flush_interval_milliseconds>
</query_log>
```

**Comment by zhbdesign** [comment]
> https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/
> 
> ```
> <query_log>
>     <database>system</database>
>     <table>query_log</table>
>     <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
>     <flush_interval_milliseconds>7500</flush_interval_milliseconds>
> </query_log>
> ```

配置文件在线修改做好，这种需求就很容易解决了

**Comment by yuzhichang** [comment]
fixed by https://github.com/housepower/ckman/pull/85
