### ISSUE TITLE
元数据管理

### ISSUE THREAD

**Issue by lizuo123** [housepower/ckman#99]
1.在表管理里面，加上查看建表语句按钮
2.在表管理里面，加上元数据信息查看
![image](https://user-images.githubusercontent.com/24853659/122182200-a4dc3300-cebc-11eb-9753-bc78574aa0e8.png)

**Comment by YenchangChan** [comment]
we implement parts of featrue like show schema, is_readonly on #114 .
<img width="1457" alt="图片" src="https://user-images.githubusercontent.com/43897067/124548884-f2ffa900-de60-11eb-9a73-7e672ef70439.png">
